### ISSUE TITLE
CSS above-the-fold content

### ISSUE THREAD

**Issue by AlexanderSk** [yireo/pkg_scriptmerge#11]
What would you think if we would implement support to automate the creation of css above the fold content? I can see there is a library that will do: https://github.com/pocketjoso/penthouse
Many wordpress plugins exist for that use too. I believe only one plugin (not open source) supports this in joomla platform.

I would like your thoughts :)

**Comment by yireo** [comment]
I don't think this fits into ScriptMerge itself. This would need to be implemented differently in a separate Joomla module or plugin. The issue is that ScriptMerge does deal with CSS, but it does not actually understand CSS. To implement CSS-of-above-the-fold you'll need to write your own CSS and be really good at it. Customizing the Joomla template for that is much easier!

**Comment by AlexanderSk** [comment]
I would like to state the following regarding your comment.
The ScriptMerge does not understand CSS: I know what you mean but with the addition of external libraries that would be overcomed and use the Scriptmerge for this purpose too. The whole and general concept i believe is what do you wish Scriptmerge to be for? A tool for some script modifications - speed alterations or a tool that can solve any speed issue a modern website may face?
I know that i would prefer a tool - platform that could solve all the factors that google speed tests suggest that use 2-3 different tools for this. It is your choice of course ;)
